image: Visual Studio 2015

version: "1.0.{build}"
build: off
test: off
clone_folder: c:\projects\ModuleBuilder

platform:
  - x86
  - x64

environment:
  nodejs_version: 8
  GYP_MSVS_VERSION: 2015

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - cmd: SET PATH=c:\python27;%PATH%
  - cmd: SET BUILD_ONLY=true
  - cmd: npm install
  - cmd: npm run compile
  - cmd: node ci\prepare.js
  - cmd: node ci\build.js

on_success:
  - cmd: node ci\deploy.js
