on:
  push:
    tags:
      - ena-*

name: Rebuild for Electron

jobs:
  rebuild:
    name: Rebuild
    strategy:
      matrix:
        os: [windows-2016, ubuntu-16.04, macOS-10.14]
        arch: [x86, x64]
        exclude:
          - os: macOS-10.14
            arch: x86
          - os: ubuntu-16.04
            arch: x86
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print Tag Ref
        run: echo ${{ github.ref }}

      - uses: actions/checkout@master

      - name: Use Node.js 12.x
        uses: implausible/setup-node@feature/expose-architecture-override
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          node-version: 12
          node-arch: ${{ matrix.arch }}

      - name: Install Dependencies for Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          sudo apt update
          sudo apt install build-essential libssl-dev libkrb5-dev libc++-dev

      - name: Fix Node-Gyp for windows
        if: startsWith(matrix.os, 'windows')
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          npm install -g node-gyp@~6.0.1
          $nodeGypLocation=npm root -g
          npm config set node_gyp $nodeGypLocation\bin\node-gyp.js
        shell: pwsh

      - run: npm install
      - run: npm run compile
      - run: node ci/prepare.js
        env:
          electron_npg_automator_gh_token: ${{ secrets.electron_npg_automator_gh_token }}
          node_pre_gyp_bucket: ${{ secrets.node_pre_gyp_bucket }}
          node_pre_gyp_accessKeyId: ${{ secrets.node_pre_gyp_accessKeyId }}
          node_pre_gyp_secretAccessKey: ${{ secrets.node_pre_gyp_secretAccessKey }}
          CC: clang
          CXX: clang++
          npm_config_clang: 1
          GYP_DEFINES: use_obsolete_asm=true
          BUILD_ONLY: true
          electron_npg_automator_module: nodegit/nodegit
          electron_npg_automator_use_git_clone: true
      - run: node ci/build.js
        env:
          electron_npg_automator_gh_token: ${{ secrets.electron_npg_automator_gh_token }}
          node_pre_gyp_bucket: ${{ secrets.node_pre_gyp_bucket }}
          node_pre_gyp_accessKeyId: ${{ secrets.node_pre_gyp_accessKeyId }}
          node_pre_gyp_secretAccessKey: ${{ secrets.node_pre_gyp_secretAccessKey }}
          CC: clang
          CXX: clang++
          npm_config_clang: 1
          GYP_DEFINES: use_obsolete_asm=true
          BUILD_ONLY: true
          electron_npg_automator_module: nodegit/nodegit
          electron_npg_automator_use_git_clone: true
      - run: node ci/deploy.js
        env:
          electron_npg_automator_gh_token: ${{ secrets.electron_npg_automator_gh_token }}
          node_pre_gyp_bucket: ${{ secrets.node_pre_gyp_bucket }}
          node_pre_gyp_accessKeyId: ${{ secrets.node_pre_gyp_accessKeyId }}
          node_pre_gyp_secretAccessKey: ${{ secrets.node_pre_gyp_secretAccessKey }}
          CC: clang
          CXX: clang++
          npm_config_clang: 1
          GYP_DEFINES: use_obsolete_asm=true
          BUILD_ONLY: true
          electron_npg_automator_module: nodegit/nodegit
          electron_npg_automator_use_git_clone: true
